

package servicecore;

import java.util.*;
import java.io.Serializable;
import de.hybris.platform.util.*;
import de.hybris.platform.core.*;
import de.hybris.platform.jalo.JaloBusinessException;
import de.hybris.platform.jalo.type.*;
import de.hybris.platform.persistence.type.*;
import de.hybris.platform.persistence.enumeration.*;
import de.hybris.platform.persistence.property.PersistenceManager;
import de.hybris.platform.persistence.*;

/**
 * Generated by hybris Platform.
 */
@SuppressWarnings({"cast","unused","boxing","null", "PMD"})
public class GeneratedTypeInitializer extends AbstractTypeInitializer
{
	/**
	 * Generated by hybris Platform.
	 */
	public GeneratedTypeInitializer( ManagerEJB manager, Map params )
	{
		super( manager, params );
	}


	/**
	 * Generated by hybris Platform.
	 */
	@Override
	protected void performRemoveObjects( ManagerEJB manager, Map params ) throws JaloBusinessException
	{
		// no-op by now
	}

	/**
	 * Generated by hybris Platform.
	 */
	@Override
	protected final void performCreateTypes( final ManagerEJB manager, Map params ) throws JaloBusinessException
	{
		// performCreateTypes
	
	
		createItemType(
			"CustomerHealthData",
			"GenericItem",
			com.acc.jalo.CustomerHealthData.class,
			"de.hybris.platform.persistence.servicecore_CustomerHealthData",
			false,
			null,
			false
		);
	
		createItemType(
			"Beacon",
			"GenericItem",
			com.acc.jalo.Beacon.class,
			"de.hybris.platform.persistence.servicecore_Beacon",
			false,
			null,
			false
		);
	
		createItemType(
			"EmailEligibleCustomersForPromotionsCronJob",
			"CronJob",
			com.acc.jalo.cronjob.EmailEligibleCustomersForPromotionsCronJob.class,
			null,
			false,
			null,
			false
		);
	
		createItemType(
			"CustomerPromotionsProcess",
			"StoreFrontCustomerProcess",
			com.acc.jalo.CustomerPromotionsProcess.class,
			null,
			false,
			null,
			false
		);
	
		createRelationType(
			"Beacon2PromotionsRel",
			"de.hybris.platform.persistence.link.servicecore_Beacon2PromotionsRel",
			false
		);
	
		createCollectionType(
			"PromotionsCollection",
			"AbstractPromotion",
			CollectionType.COLLECTION
		);
	
	}

	/**
	 * Generated by hybris Platform.
	 */
	@Override
	protected final void performModifyTypes( final ManagerEJB manager, Map params ) throws JaloBusinessException
	{
		// performModifyTypes
	

	
	
				single_createattr_CustomerHealthData_customerId();
			
				single_createattr_CustomerHealthData_hkCategoryTypeIdentifierSleepAnalysis ();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierBodyMass ();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierBodyMassIndex();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierBodyFatPercentage();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierHeartRate();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierBloodPressureSystolic();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierStepCount();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierRespiratoryRate();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDistanceCycling();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierOxygenSaturation();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDistanceWalkingRunning();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryManganese();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierBasalEnergyBurned();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryCalcium();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryFiber();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierBloodPressureDiastolic();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryFatSaturated();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierFlightsClimbed();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryMagnesium();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryIron();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryCopper();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryPotassium();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryPantothenicAcid();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryCaffeine();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryFatPolyunsaturated();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryFatMonounsaturated();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryNiacin();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryChromium();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryCarbohydrates();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryVitaminK();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryFolate();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryBiotin();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryCholesterol();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietarySodium();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryMolybdenum();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryChloride();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryIodine();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryPhosphorus();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietarySugar();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryEnergyConsumed();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierActiveEnergyBurned();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryVitaminB6();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryZinc();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryFatTotal();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryVitaminE();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryVitaminA();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryVitaminD();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryVitaminC();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryThiamin();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryRiboflavin();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryProtein();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryVitaminB12();
			
				single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietarySelenium();
			
				single_createattr_Beacon_identifier();
			
				single_createattr_Beacon_majorId ();
			
				single_createattr_Beacon_minorId ();
			
				single_createattr_Beacon_welcomeMessage();
			
				single_createattr_Product_beaconId();
			
				single_createattr_Product_location();
			
				single_createattr_CustomerPromotionsProcess_promotionsList();
			
		createRelationAttributes(
			"Beacon2PromotionsRel", 
			false, 

			"beacons", 
			"Beacon", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			true,
			CollectionType.LIST,
			"promotions", 
			"AbstractPromotion", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			true,
			CollectionType.LIST
		);
	

	}

	
	public void single_createattr_CustomerHealthData_customerId() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"customerId",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkCategoryTypeIdentifierSleepAnalysis () throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkCategoryTypeIdentifierSleepAnalysis ",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierBodyMass () throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierBodyMass ",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierBodyMassIndex() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierBodyMassIndex",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierBodyFatPercentage() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierBodyFatPercentage",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierHeartRate() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierHeartRate",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierBloodPressureSystolic() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierBloodPressureSystolic",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierStepCount() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierStepCount",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierRespiratoryRate() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierRespiratoryRate",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDistanceCycling() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierDistanceCycling",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierOxygenSaturation() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierOxygenSaturation",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDistanceWalkingRunning() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierDistanceWalkingRunning",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryManganese() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierDietaryManganese",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierBasalEnergyBurned() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierBasalEnergyBurned",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryCalcium() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierDietaryCalcium",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryFiber() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierDietaryFiber",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierBloodPressureDiastolic() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierBloodPressureDiastolic",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryFatSaturated() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierDietaryFatSaturated",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierFlightsClimbed() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierFlightsClimbed",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryMagnesium() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierDietaryMagnesium",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryIron() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierDietaryIron",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryCopper() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierDietaryCopper",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryPotassium() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierDietaryPotassium",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryPantothenicAcid() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierDietaryPantothenicAcid",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryCaffeine() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierDietaryCaffeine",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryFatPolyunsaturated() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierDietaryFatPolyunsaturated",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryFatMonounsaturated() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierDietaryFatMonounsaturated",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryNiacin() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierDietaryNiacin",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryChromium() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierDietaryChromium",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryCarbohydrates() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierDietaryCarbohydrates",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryVitaminK() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierDietaryVitaminK",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryFolate() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierDietaryFolate",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryBiotin() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierDietaryBiotin",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryCholesterol() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierDietaryCholesterol",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietarySodium() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierDietarySodium",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryMolybdenum() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierDietaryMolybdenum",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryChloride() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierDietaryChloride",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryIodine() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierDietaryIodine",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryPhosphorus() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierDietaryPhosphorus",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietarySugar() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierDietarySugar",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryEnergyConsumed() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierDietaryEnergyConsumed",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierActiveEnergyBurned() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierActiveEnergyBurned",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryVitaminB6() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierDietaryVitaminB6",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryZinc() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierDietaryZinc",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryFatTotal() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierDietaryFatTotal",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryVitaminE() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierDietaryVitaminE",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryVitaminA() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierDietaryVitaminA",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryVitaminD() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierDietaryVitaminD",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryVitaminC() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierDietaryVitaminC",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryThiamin() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierDietaryThiamin",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryRiboflavin() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierDietaryRiboflavin",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryProtein() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierDietaryProtein",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietaryVitaminB12() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierDietaryVitaminB12",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerHealthData_hkQuantityTypeIdentifierDietarySelenium() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerHealthData", 
					"hkQuantityTypeIdentifierDietarySelenium",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_Beacon_identifier() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"Beacon", 
					"identifier",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_Beacon_majorId () throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"Beacon", 
					"majorId ",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_Beacon_minorId () throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"Beacon", 
					"minorId ",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_Beacon_welcomeMessage() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"Beacon", 
					"welcomeMessage",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_Product_beaconId() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"Product", 
					"beaconId",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_Product_location() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"Product", 
					"location",  
					null,
					"java.lang.String",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	
	public void single_createattr_CustomerPromotionsProcess_promotionsList() throws JaloBusinessException
	{
		
						Map sqlColumnDefinitions = null;
					
				createPropertyAttribute(
					"CustomerPromotionsProcess", 
					"promotionsList",  
					null,
					"PromotionsCollection",
					de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG,
					null,
					sqlColumnDefinitions
				);
			
	}
	


	/**
	 * Generated by hybris Platform.
	 */
	@Override
	protected final void performCreateObjects( final ManagerEJB manager, Map params ) throws JaloBusinessException
	{
		// performCreateObjects
	
	
		single_setRelAttributeProperties_Beacon2PromotionsRel_source();
	
		single_setRelAttributeProperties_Beacon2PromotionsRel_target();
	
		connectRelation(
			"Beacon2PromotionsRel", 
			false, 
			"beacons", 
			"Beacon", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			"promotions", 
			"AbstractPromotion", 
			true,
			de.hybris.platform.jalo.type.AttributeDescriptor.READ_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.WRITE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.OPTIONAL_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.REMOVE_FLAG|de.hybris.platform.jalo.type.AttributeDescriptor.SEARCH_FLAG, 
			true,
			true
		);
	
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"CustomerHealthData",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_CustomerHealthData_customerId();
		
			single_setAttributeProperties_CustomerHealthData_hkCategoryTypeIdentifierSleepAnalysis ();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierBodyMass ();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierBodyMassIndex();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierBodyFatPercentage();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierHeartRate();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierBloodPressureSystolic();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierStepCount();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierRespiratoryRate();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDistanceCycling();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierOxygenSaturation();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDistanceWalkingRunning();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryManganese();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierBasalEnergyBurned();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryCalcium();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryFiber();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierBloodPressureDiastolic();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryFatSaturated();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierFlightsClimbed();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryMagnesium();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryIron();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryCopper();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryPotassium();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryPantothenicAcid();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryCaffeine();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryFatPolyunsaturated();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryFatMonounsaturated();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryNiacin();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryChromium();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryCarbohydrates();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryVitaminK();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryFolate();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryBiotin();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryCholesterol();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietarySodium();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryMolybdenum();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryChloride();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryIodine();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryPhosphorus();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietarySugar();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryEnergyConsumed();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierActiveEnergyBurned();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryVitaminB6();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryZinc();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryFatTotal();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryVitaminE();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryVitaminA();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryVitaminD();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryVitaminC();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryThiamin();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryRiboflavin();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryProtein();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryVitaminB12();
		
			single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietarySelenium();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"Beacon",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_Beacon_identifier();
		
			single_setAttributeProperties_Beacon_majorId ();
		
			single_setAttributeProperties_Beacon_minorId ();
		
			single_setAttributeProperties_Beacon_welcomeMessage();
		
				{
				Map customPropsMap = new HashMap();
				
				changeMetaType(
					"Product",
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_Product_beaconId();
		
			single_setAttributeProperties_Product_location();
		
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"EmailEligibleCustomersForPromotionsCronJob",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
				{
				Map customPropsMap = new HashMap();
				
				setItemTypeProperties(
					"CustomerPromotionsProcess",
					false,
					true,
					true,
					null,
					customPropsMap
				);
				}
			
			single_setAttributeProperties_CustomerPromotionsProcess_promotionsList();
		
				setDefaultProperties(
					"PromotionsCollection",
					true,
					false,
					null
				);
			
	}


		
						public void single_setAttributeProperties_CustomerHealthData_customerId() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"customerId",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkCategoryTypeIdentifierSleepAnalysis () throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkCategoryTypeIdentifierSleepAnalysis ",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierBodyMass () throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierBodyMass ",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierBodyMassIndex() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierBodyMassIndex",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierBodyFatPercentage() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierBodyFatPercentage",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierHeartRate() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierHeartRate",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierBloodPressureSystolic() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierBloodPressureSystolic",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierStepCount() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierStepCount",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierRespiratoryRate() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierRespiratoryRate",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDistanceCycling() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierDistanceCycling",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierOxygenSaturation() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierOxygenSaturation",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDistanceWalkingRunning() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierDistanceWalkingRunning",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryManganese() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierDietaryManganese",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierBasalEnergyBurned() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierBasalEnergyBurned",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryCalcium() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierDietaryCalcium",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryFiber() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierDietaryFiber",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierBloodPressureDiastolic() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierBloodPressureDiastolic",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryFatSaturated() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierDietaryFatSaturated",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierFlightsClimbed() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierFlightsClimbed",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryMagnesium() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierDietaryMagnesium",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryIron() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierDietaryIron",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryCopper() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierDietaryCopper",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryPotassium() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierDietaryPotassium",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryPantothenicAcid() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierDietaryPantothenicAcid",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryCaffeine() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierDietaryCaffeine",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryFatPolyunsaturated() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierDietaryFatPolyunsaturated",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryFatMonounsaturated() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierDietaryFatMonounsaturated",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryNiacin() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierDietaryNiacin",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryChromium() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierDietaryChromium",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryCarbohydrates() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierDietaryCarbohydrates",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryVitaminK() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierDietaryVitaminK",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryFolate() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierDietaryFolate",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryBiotin() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierDietaryBiotin",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryCholesterol() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierDietaryCholesterol",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietarySodium() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierDietarySodium",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryMolybdenum() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierDietaryMolybdenum",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryChloride() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierDietaryChloride",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryIodine() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierDietaryIodine",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryPhosphorus() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierDietaryPhosphorus",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietarySugar() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierDietarySugar",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryEnergyConsumed() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierDietaryEnergyConsumed",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierActiveEnergyBurned() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierActiveEnergyBurned",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryVitaminB6() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierDietaryVitaminB6",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryZinc() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierDietaryZinc",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryFatTotal() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierDietaryFatTotal",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryVitaminE() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierDietaryVitaminE",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryVitaminA() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierDietaryVitaminA",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryVitaminD() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierDietaryVitaminD",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryVitaminC() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierDietaryVitaminC",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryThiamin() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierDietaryThiamin",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryRiboflavin() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierDietaryRiboflavin",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryProtein() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierDietaryProtein",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietaryVitaminB12() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierDietaryVitaminB12",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerHealthData_hkQuantityTypeIdentifierDietarySelenium() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerHealthData", 
								"hkQuantityTypeIdentifierDietarySelenium",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_Beacon_identifier() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"Beacon", 
								"identifier",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_Beacon_majorId () throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"Beacon", 
								"majorId ",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_Beacon_minorId () throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"Beacon", 
								"minorId ",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_Beacon_welcomeMessage() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"Beacon", 
								"welcomeMessage",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_Product_beaconId() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"Product", 
								"beaconId",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_Product_location() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"Product", 
								"location",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
						public void single_setAttributeProperties_CustomerPromotionsProcess_promotionsList() throws JaloBusinessException
						{
							
							
							
							Map customPropsMap = new HashMap();
							
							setAttributeProperties(
								"CustomerPromotionsProcess", 
								"promotionsList",
								false, 
								null,
								null,
								null,
								true,
								true,
								null,
								customPropsMap,
								null
							);
						}
					
								public void single_setRelAttributeProperties_Beacon2PromotionsRel_source() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"AbstractPromotion", 
										"beacons",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
								public void single_setRelAttributeProperties_Beacon2PromotionsRel_target() throws JaloBusinessException
								{
									
									Map customPropsMap = new HashMap();
									

									setAttributeProperties(
										"Beacon", 
										"promotions",
										false, 
										null,
										null,
										null,
										true,
										true,
										null,
										customPropsMap,
										null
									);
								}
							
}

	